Remove multinode e2e tests from the e2e target
Multinode is not supported and running the e2e tests with the flag
causes the following error when creating the extension:

CREATE EXTENSION IF NOT EXISTS promscale VERSION '0.5.4';

ERROR:  [dn0]: schema "ps_trace" does not exist