Compare for context.Canceled error with `Is`
Since `context.Caceled` is declared as:

```
var Canceled = errors.New("context canceled")
```

We should use `errors.Is` instead of `errors.As` because we are
comparing against and error value instead of the type of the error.

golangci-lint reports the current usage of `errors.As` with the
following error:

```
golangci-lint run
pkg/runner/runner.go:61:20: errorsas: second argument to errors.As should not be *error (govet)
        if err != nil && !errors.As(err, &context.Canceled) {
                          ^
pkg/runner/runner.go:69:20: errorsas: second argument to errors.As should not be *error (govet)
        if err != nil && !errors.As(err, &context.Canceled) {
```