Commit that causes
ERROR: trigger "compressed_chunk_insert_blocker" for relation "_hyper_1_1_chunk" already exists

run

go test -v -run TestSQLGoldenFiles ./pkg/pgmodel/end_to_end_tests -use-timescale2 -use-extension=false

to repro